name = "NonconvexSearch"
uuid = "75732972-a7cd-4375-b200-958e0814350d"
version = "0.1.3"
authors = ["Mohamed Tarek <mohdibntarek@gmail.com> and contributors"]

[deps]
NonconvexCore = "035190e5-69f1-488f-aaab-becca2889735"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
NonconvexCore = "1.5"
Parameters = "0.12, 0.13"
Random = "1.11.0"
Reexport = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
